name: Test App
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v4
      - name: Cache dependecies
        uses: actions/cache@v4
        with:
            path: ~/.npm
            key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependecies
        run: npm ci
      - name: Test
        run: npm run test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get the repository code
        uses: actions/checkout@v4
      - name: Install nodeJS
        uses: actions/setup-node@v4
        with: 
          node-version: 20
      - name: Cache dependecies
        uses: actions/cache@v4
        with:
            path: ~/.npm
            key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependecies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: 'dist'
          name: 'build-files'
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get build project
        uses: actions/download-artifact@v4
        with: 
          name: 'build-files'